const superHerois = [
  {
    nome: "Super-Homem",
    caracteristicas: {
      homem: 1,
      bem: 1,
      capa: 1,
      mascara: 0,
      tecnologia: 0,
      armadura: 0,
      dc: 1,
      marvel: 0,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 1,
      superVelocidade: 1,
      superForca: 1,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 1,
    },
  },
  {
    nome: "Homem de Ferro",
    caracteristicas: {
      homem: 1,
      bem: 1,
      capa: 0,
      mascara: 1,
      tecnologia: 1,
      armadura: 1,
      dc: 0,
      marvel: 1,
      inteligente: 1,
      rico: 1,
      poderes: 1,
      voar: 1,
      superVelocidade: 0,
      superForca: 1,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Capitao Patria",
    caracteristicas: {
      homem: 1,
      bem: 1,
      capa: 1,
      mascara: 1,
      tecnologia: 0,
      armadura: 0,
      dc: 0,
      marvel: 0,
      inteligente: 0,
      rico: 0,
      poderes: 1,
      voar: 0,
      superVelocidade: 0,
      superForca: 1,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Homem Aranha",
    caracteristicas: {
      homem: 1,
      bem: 1,
      capa: 0,
      mascara: 1,
      tecnologia: 0,
      armadura: 0,
      dc: 0,
      marvel: 1,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 0,
      superVelocidade: 0,
      superForca: 1,
      lancaTeia: 1,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Flash",
    caracteristicas: {
      homem: 1,
      bem: 1,
      capa: 0,
      mascara: 1,
      tecnologia: 0,
      armadura: 0,
      dc: 1,
      marvel: 0,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 0,
      superVelocidade: 1,
      superForca: 0,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Trem-Bala",
    caracteristicas: {
      homem: 1,
      bem: 1,
      capa: 0,
      mascara: 1,
      tecnologia: 0,
      armadura: 0,
      dc: 0,
      marvel: 0,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 0,
      superVelocidade: 1,
      superForca: 0,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Mulher-Maravilha",
    caracteristicas: {
      homem: 0,
      bem: 1,
      capa: 1,
      mascara: 0,
      tecnologia: 0,
      armadura: 0,
      dc: 1,
      marvel: 0,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 1,
      superVelocidade: 0,
      superForca: 1,
      lancaTeia: 0,
      lacoVerdade: 1,
      sNoPeito: 0,
    },
  },
  {
    nome: "Rainha Maeve",
    caracteristicas: {
      homem: 0,
      bem: 1,
      capa: 1,
      mascara: 0,
      tecnologia: 0,
      armadura: 0,
      dc: 0,
      marvel: 0,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 0,
      superVelocidade: 0,
      superForca: 1,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Viuva Negra",
    caracteristicas: {
      homem: 0,
      bem: 1,
      capa: 0,
      mascara: 1,
      tecnologia: 1,
      armadura: 0,
      dc: 0,
      marvel: 1,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 0,
      superVelocidade: 0,
      superForca: 0,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Mulher Invisivel",
    caracteristicas: {
      homem: 0,
      bem: 1,
      capa: 0,
      mascara: 0,
      tecnologia: 0,
      armadura: 0,
      dc: 0,
      marvel: 0,
      inteligente: 1,
      rico: 0,
      poderes: 1,
      voar: 0,
      superVelocidade: 0,
      superForca: 0,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
  {
    nome: "Batman",
    caracteristicas: {
      homem: 1,
      bem: 1,
      capa: 1,
      mascara: 1,
      tecnologia: 1,
      armadura: 1,
      dc: 1,
      marvel: 0,
      inteligente: 1,
      rico: 1,
      poderes: 1,
      voar: 0,
      superVelocidade: 0,
      superForca: 0,
      lancaTeia: 0,
      lacoVerdade: 0,
      sNoPeito: 0,
    },
  },
];

const perguntas = [
  {
    pergunta: "Seu herói é homem?",
    caracteristica: ["homem"],
  },
  {
    pergunta: "Seu herói é do bem?",
    caracteristica: ["bem"],
  },
  {
    pergunta: "Seu herói Usa Capa?",
    caracteristica: ["capa"],
  },
  {
    pergunta: "Seu herói usa Máscara?",
    caracteristica: ["mascara"],
  },
  {
    pergunta: "Seu herói usa Tecnologia?",
    caracteristica: ["tecnologia"],
  },
  {
    pergunta: "Seu herói usa Armadura?",
    caracteristica: ["armadura"],
  },
  {
    pergunta: "Seu herói é da DC?",
    caracteristica: ["dc"],
  },
  {
    pergunta: "Seu herói é da Marvel?",
    caracteristica: ["marvel"],
  },
  {
    pergunta: "Seu herói é inteligente?",
    caracteristica: ["inteligente"],
  },
  {
    pergunta: "Seu herói é rico?",
    caracteristica: ["rico"],
  },
  {
    pergunta: "Seu herói tem poderes?",
    caracteristica: ["poderes"],
  },
  {
    pergunta: "Seu herói voa?",
    caracteristica: ["voar"],
  },
  {
    pergunta: "Seu herói tem super velocidade?",
    caracteristica: ["superVelocidade"],
  },
  {
    pergunta: "Seu herói tem super força?",
    caracteristica: ["superForca"],
  },
  {
    pergunta: "Seu herói lança teia?",
    caracteristica: ["lancaTeia"],
  },
  {
    pergunta: "Seu herói tem um laço da verdade?",
    caracteristica: ["lacoVerdade"],
  },
  {
    pergunta: "Seu herói tem um 'S' no peito?",
    caracteristica: ["sNoPeito"],
  },
];

export { superHerois, perguntas };
